# 初始化环境
- name: Init Environment
  hosts: new_nodes
  roles:
    - init
  tags: init

# 安装 nodes
- name: Install Node Cluster
  hosts: new_nodes
  roles:
    - node
  tags: node

# 安装 网路插件
- name: Install Network Plugins
  hosts: nodes
  roles:
    - { role: flannel, tags: flannel,  when: network_type == 'flannel' }
    - { role: calico, tags: calico,  when: network_type == 'calico' }
  tags: network
