# 安装 nginx
- name: nginx
  hosts: local
  roles:
    - nginx
  tags: nginx

# 初始化环境
- name: init
  hosts: k8s
  roles:
    - init
  tags: init

# 创建证书
- name: cert
  hosts: local
  roles:
    - cert
  tags: cert

# 安装 etcd
- name: Install Etcd Cluster
  hosts: masters
  roles:
    - etcd
  tags: etcd

# 安装 masters
- name: Install Master Cluster
  hosts: masters
  roles:
    - master
  tags: master

# 安装 nodes
- name: Install Node Cluster
  hosts: nodes
  roles:
    - node
  tags: node

# 安装 flannel
- name: Install Network Plugins
  hosts: nodes
  roles:
    - network
  tags: network

# 安装 coredns
- name: Install Coredns 
  hosts: masters
  roles:
    - coredns
  tags: coredns

# 安装 metrics
- name: Install Metrics-server 
  hosts: masters
  roles:
    - metrics-server
  tags: metrics