# 初始化环境
- name: init
  hosts: k8s
  roles:
    - init
  tags: init

# 创建证书
- name: cert
  hosts: local
  roles:
    - cert
  tags: cert

# 安装 etcd
- name: Install Etcd Cluster
  hosts: masters
  roles:
    - etcd
  tags: etcd