# Create some dir

- name: "Make Etcd Directory"
  file:
    name: "{{workdir}}/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - etcd
    - etcd/bin
    - etcd/cfg
    - etcd/ssl
    - etcd/data