- name: "Create Dir yaml"
  file:
    name: "{{ workdir }}/yamls"
    state: directory
    recurse: true

- name: "Copy Coredns.yaml Files"
  template:
    src: coredns.yaml.j2
    dest: "{{workdir}}/yamls/coredns.yaml"

- name: "Run 'kubectl apply -f coredns.yaml'"
  shell:
    "kubectl apply -f coredns.yaml"
  args:
    chdir: "{{ workdir }}/yamls"
  run_once: true