- name: "Add Kubelet-bootstrap RoleBinding For A CSR Is Automatically Created when a Kubelet is started "
  shell: |
    sleep 10
    kubectl  create  clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --user=kubelet-bootstrap
  run_once: true
  ignore_errors: true

- name: "Create Dir yaml"
  file:
    name: "{{ workdir }}/yamls"
    state: directory
    recurse: true
  run_once: true

- name: "Copy File tls-instructs-csr.yaml"
  copy:
    src: tls-instructs-csr.yaml
    dest: "{{ workdir }}/yamls"
  run_once: true  

- name: "Create Approve CSR ClusterRole" 
  shell: |
    sleep 10
    kubectl apply -f tls-instructs-csr.yaml
  args:
    chdir: "{{ workdir }}/yamls"
  run_once: true 

- name: "Create Approve CSR ClusterRoleBinding"
  shell: |
    sleep 10
    kubectl create clusterrolebinding node-client-auto-approve-csr --clusterrole=system:certificates.k8s.io:certificatesigningrequests:nodeclient --user=kubelet-bootstrap
  run_once: true
  ignore_errors: true

- name: "Create CRT Renew ClusterRoleBinding"
  shell: |
    sleep 10
    kubectl create clusterrolebinding node-client-auto-renew-crt --clusterrole=system:certificates.k8s.io:certificatesigningrequests:selfnodeclient --group=system:nodes
    kubectl create clusterrolebinding node-server-auto-renew-crt --clusterrole=system:certificates.k8s.io:certificatesigningrequests:selfnodeserver --group=system:nodes
  run_once: true
  ignore_errors: true

- name: "Create kubelet-api-admin clusterRoleBinding To Access Log Or Exec"
  shell: |
    sleep 10
    kubectl create clusterrolebinding kubelet-api-admin --user=kubernetes --clusterrole=cluster-admin
  run_once: true
  ignore_errors: true

