- name: "Distribute K8s Master Binary File"
  copy:
    src: "{{ package_root_dir }}/k8s/{{ etcd_version }}/kubernetes/server/bin/{{ item }}"
    dest: "{{ workdir }}/kubernetes/bin"
    mode: 0755
  with_items:
    - kubectl
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: "Distribute K8s Certs"
  copy:
    src: "{{cert_root_dir}}/{{ item }}"
    dest: "{{workdir}}/kubernetes/ssl/"
  with_items:
    - ca.pem
    - ca.key
    - server.pem
    - server-key.pem
    - metrics-server.pem
    - metrics-server-key.pem

- name: "Write Kubectl Command to Profile"
  template:
    src: kubectl.sh.j2
    dest: /etc/profile.d/kubectl.sh
    mode: 0755


