# Create some dir

- name: "Make Master Directory"
  file:
    name: "{{workdir}}/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - etcd
    - etcd/bin
    - etcd/cfg
    - etcd/ssl
    - etcd/data
    - kubernetes
    - kubernetes/bin
    - kubernetes/cfg
    - kubernetes/ssl
    - kubernetes/logs
    - kubernetes/logs/kubelet
    - kubernetes/logs/kube-proxy
    - kubernetes/logs/kube-scheduler
    - kubernetes/logs/kube-apiserver
    - kubernetes/logs/kube-controller-manager

- name: "Make Nodes Directory"
  file:
    name: "{{workdir}}/{{ item }}"
    state: directory
    recurse: true
  with_items:
    - kubernetes
    - kubernetes/bin
    - kubernetes/cfg
    - kubernetes/ssl
    - kubernetes/logs
    - kubernetes/logs/kubelet
    - kubernetes/logs/kube-proxy
