# Disable Selinux
  - name: Change selinux config file
    lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX=enforcing'
      line: SELINUX=disabled
  - name: Exec setenforce 0 command
    shell: setenforce 0