  - name: Install new packages
    yum:
      name: ['conntrack', 'ipvsadm', 'ipset', 'iptables-services', 'libseccomp', 'jq', 'sysstat', 'curl', 'wget', 'net-tools', 'telnet', 'vim', 'socat']
#      name: "{{ item }}"
      state: present
#    with_items:
#      - conntrack
#      - ipvsadm
#      - ipset
#      - iptables-services
#      - libseccomp
#      - jq
#      - sysstat
#      - curl
#      - wget
#      - net-tools
#      - telnet
#      - vim
#      - socat
#      - chrony

